# Generated by Django 4.2.7 on 2023-12-03 07:10

import admissions.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=1000, verbose_name='Student Name')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('guardian_name', models.CharField(max_length=1000, verbose_name='Father / Guardian name')),
                ('contact_no', models.CharField(max_length=20, verbose_name='Contact Number')),
                ('alt_contact_number', models.CharField(max_length=20, verbose_name='ALternate Contact Number')),
                ('email_id', models.EmailField(max_length=254, verbose_name='Email ID')),
                ('course_category', models.CharField(max_length=1000, verbose_name='Course Category')),
                ('course_name', models.CharField(max_length=1000, verbose_name='Course Name')),
                ('college_location', models.CharField(max_length=1000, verbose_name='Location of the college')),
                ('year_12th', models.CharField(max_length=10, verbose_name='Year in which student passed 12th')),
                ('examination_board', models.CharField(max_length=1000, verbose_name='Examination board')),
                ('college_name', models.CharField(max_length=1000, verbose_name='Name of School / College in which you study 12th')),
                ('grade_12th', models.CharField(max_length=10, verbose_name='12th Passing Grade or Percentage')),
                ('entrance_exam', models.CharField(max_length=1000, verbose_name='Have you written any of the Entrance Exam this year?')),
                ('identification_proof', models.FileField(upload_to=admissions.models.student_documents, verbose_name='Identification Proof')),
                ('marks_card_12th', models.FileField(blank=True, null=True, upload_to=admissions.models.student_documents, verbose_name='12th Marks card')),
                ('marks_card_10th', models.FileField(upload_to=admissions.models.student_documents, verbose_name='10th Marks card')),
                ('photo', models.FileField(upload_to=admissions.models.student_documents, verbose_name='Passport Size Photo')),
                ('signature', models.FileField(upload_to=admissions.models.student_documents, verbose_name='Signature Copy')),
                ('migration_cert', models.FileField(blank=True, null=True, upload_to=admissions.models.student_documents, verbose_name='Migration Certificate:')),
                ('score_card', models.FileField(blank=True, null=True, upload_to=admissions.models.student_documents, verbose_name='KCET, NEET, JEE etc Rank / Score Card')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
