# Generated by Django 4.2.7 on 2023-12-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_rename_college_name_managementstudent_college_name_12th'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementstudent',
            name='applied',
            field=models.BooleanField(default=False),
        ),
    ]
