# Generated by Django 4.2.7 on 2023-12-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_managementstudent_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementstudent',
            name='college_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='College name'),
        ),
    ]
