# Generated by Django 4.1.3 on 2022-11-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatmatrix',
            name='accreditation',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Accreditation'),
        ),
    ]
