# Generated by Django 4.1.3 on 2022-11-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_seatmatrix_accreditation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatmatrix',
            name='accreditation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Accreditation'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='affiliation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Affiliation'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='annexure',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Annexure'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='college_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='College Code'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='college_operation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='College Operation'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='college_ownership_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='College Ownership Type'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='seatmatrix',
            name='seat_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Seat Type'),
        ),
    ]
