# Generated by Django 4.2 on 2023-04-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_seatmatrix_accreditation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cutoff',
            name='H_1G',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='H_1K',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='H_1R',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='H_2AG',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='H_2AK',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='H_2AR',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='H_2BG',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='H_2BK',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='H_2BR',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='H_3AG',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='H_3AK',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='H_3AR',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='H_3BG',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='H_3BK',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='H_3BR',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='H_GM',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='H_GMK',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='H_GMR',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='H_SCG',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='H_SCK',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='H_SCR',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='H_STG',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='H_STK',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='H_STR',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='_1G',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='_1K',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='_1R',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='_2AG',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='_2AK',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='_2AR',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='_2BG',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='_2BK',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='_2BR',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='_3AG',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='_3AK',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='_3AR',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='_3BG',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='_3BK',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='_3BR',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='_GM',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='_GMK',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='_GMP',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='_GMR',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='_SCG',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='_SCK',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='_SCR',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='_STG',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='_STK',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='_STR',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='category',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='code',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='college',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='course',
        ),
        migrations.RemoveField(
            model_name='cutoff',
            name='round',
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_1h',
            field=models.IntegerField(blank=True, null=True, verbose_name='1H'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_1kh',
            field=models.IntegerField(blank=True, null=True, verbose_name='1KH'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_1rh',
            field=models.IntegerField(blank=True, null=True, verbose_name='1RH'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_2ah',
            field=models.IntegerField(blank=True, null=True, verbose_name='2AH'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_2akh',
            field=models.IntegerField(blank=True, null=True, verbose_name='2AKH'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_2arh',
            field=models.IntegerField(blank=True, null=True, verbose_name='2ARH'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_2bh',
            field=models.IntegerField(blank=True, null=True, verbose_name='2BH'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_2bkh',
            field=models.IntegerField(blank=True, null=True, verbose_name='2BKH'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_2brh',
            field=models.IntegerField(blank=True, null=True, verbose_name='2BRH'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_3ah',
            field=models.IntegerField(blank=True, null=True, verbose_name='3AH'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_3akh',
            field=models.IntegerField(blank=True, null=True, verbose_name='3AKH'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_3arh',
            field=models.IntegerField(blank=True, null=True, verbose_name='3ARH'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_3bh',
            field=models.IntegerField(blank=True, null=True, verbose_name='3BH'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_3bkh',
            field=models.IntegerField(blank=True, null=True, verbose_name='3BKH'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_3brh',
            field=models.IntegerField(blank=True, null=True, verbose_name='3BRH'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_college_code',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='College Code'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_college_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='College Name'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_course_code',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Course Code'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_course_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Course Name'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_gmh',
            field=models.IntegerField(blank=True, null=True, verbose_name='GMH'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_gmkh',
            field=models.IntegerField(blank=True, null=True, verbose_name='GMKH'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_gmph',
            field=models.IntegerField(blank=True, null=True, verbose_name='GMPH'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_gmrh',
            field=models.IntegerField(blank=True, null=True, verbose_name='GMRH'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_ma',
            field=models.IntegerField(blank=True, null=True, verbose_name='MA'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_mc',
            field=models.IntegerField(blank=True, null=True, verbose_name='MC'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_me',
            field=models.IntegerField(blank=True, null=True, verbose_name='ME'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_meh',
            field=models.IntegerField(blank=True, null=True, verbose_name='MEH'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_mk',
            field=models.IntegerField(blank=True, null=True, verbose_name='MK'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_mm',
            field=models.IntegerField(blank=True, null=True, verbose_name='MM'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_mmh',
            field=models.IntegerField(blank=True, null=True, verbose_name='MMH'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_mu',
            field=models.IntegerField(blank=True, null=True, verbose_name='MU'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_nri',
            field=models.IntegerField(blank=True, null=True, verbose_name='NRI'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_opn',
            field=models.IntegerField(blank=True, null=True, verbose_name='OPN'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_oth',
            field=models.IntegerField(blank=True, null=True, verbose_name='OTH'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_rc2',
            field=models.IntegerField(blank=True, null=True, verbose_name='RC2'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_rc3',
            field=models.IntegerField(blank=True, null=True, verbose_name='RC3'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_rc4',
            field=models.IntegerField(blank=True, null=True, verbose_name='RC4'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_rc5',
            field=models.IntegerField(blank=True, null=True, verbose_name='RC5'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_rc6',
            field=models.IntegerField(blank=True, null=True, verbose_name='RC6'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_rc7',
            field=models.IntegerField(blank=True, null=True, verbose_name='RC7'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_rc8',
            field=models.IntegerField(blank=True, null=True, verbose_name='RC8'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_round',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Round'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_sch',
            field=models.IntegerField(blank=True, null=True, verbose_name='SCH'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_sckh',
            field=models.IntegerField(blank=True, null=True, verbose_name='SCKH'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_scrh',
            field=models.IntegerField(blank=True, null=True, verbose_name='SCRH'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_sth',
            field=models.IntegerField(blank=True, null=True, verbose_name='STH'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_stkh',
            field=models.IntegerField(blank=True, null=True, verbose_name='STKH'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_strh',
            field=models.IntegerField(blank=True, null=True, verbose_name='STRH'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_type',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_year',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Year'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_1g',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='1G'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_1k',
            field=models.IntegerField(blank=True, null=True, verbose_name='1K'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_1r',
            field=models.IntegerField(blank=True, null=True, verbose_name='1R'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_2ag',
            field=models.IntegerField(blank=True, null=True, verbose_name='2AG'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_2ak',
            field=models.IntegerField(blank=True, null=True, verbose_name='2AK'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_2ar',
            field=models.IntegerField(blank=True, null=True, verbose_name='2AR'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_2bg',
            field=models.IntegerField(blank=True, null=True, verbose_name='2BG'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_2bk',
            field=models.IntegerField(blank=True, null=True, verbose_name='2BK'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_2br',
            field=models.IntegerField(blank=True, null=True, verbose_name='2BR'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_3ag',
            field=models.IntegerField(blank=True, null=True, verbose_name='3AG'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_3ak',
            field=models.IntegerField(blank=True, null=True, verbose_name='3AK'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_3ar',
            field=models.IntegerField(blank=True, null=True, verbose_name='3AR'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_3bg',
            field=models.IntegerField(blank=True, null=True, verbose_name='3BG'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_3bk',
            field=models.IntegerField(blank=True, null=True, verbose_name='3BK'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_3br',
            field=models.IntegerField(blank=True, null=True, verbose_name='3BR'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_gm',
            field=models.IntegerField(blank=True, null=True, verbose_name='GM'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_gmk',
            field=models.IntegerField(blank=True, null=True, verbose_name='GMK'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_gmp',
            field=models.IntegerField(blank=True, null=True, verbose_name='GMP'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_gmr',
            field=models.IntegerField(blank=True, null=True, verbose_name='GMR'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_scg',
            field=models.IntegerField(blank=True, null=True, verbose_name='SCG'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_sck',
            field=models.IntegerField(blank=True, null=True, verbose_name='SCK'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_scr',
            field=models.IntegerField(blank=True, null=True, verbose_name='SCR'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_stg',
            field=models.IntegerField(blank=True, null=True, verbose_name='STG'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_stk',
            field=models.IntegerField(blank=True, null=True, verbose_name='STK'),
        ),
        migrations.AddField(
            model_name='cutoff',
            name='_str',
            field=models.IntegerField(blank=True, null=True, verbose_name='STR'),
        ),
    ]
