# Generated by Django 4.2 on 2023-04-10 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_cutoff_h_1g_remove_cutoff_h_1k_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seatmatrix',
            old_name='agl',
            new_name='_agl',
        ),
        migrations.RenameField(
            model_name='seatmatrix',
            old_name='cap',
            new_name='_cap',
        ),
        migrations.RenameField(
            model_name='seatmatrix',
            old_name='college_name',
            new_name='_college_name',
        ),
        migrations.RenameField(
            model_name='seatmatrix',
            old_name='course_name',
            new_name='_course_name',
        ),
        migrations.RenameField(
            model_name='seatmatrix',
            old_name='d',
            new_name='_d',
        ),
        migrations.RenameField(
            model_name='seatmatrix',
            old_name='dk',
            new_name='_dk',
        ),
        migrations.RenameField(
            model_name='seatmatrix',
            old_name='gm',
            new_name='_gm',
        ),
        migrations.RenameField(
            model_name='seatmatrix',
            old_name='gmh',
            new_name='_gmh',
        ),
        migrations.RenameField(
            model_name='seatmatrix',
            old_name='gmk',
            new_name='_gmk',
        ),
        migrations.RenameField(
            model_name='seatmatrix',
            old_name='gmkh',
            new_name='_gmkh',
        ),
        migrations.RenameField(
            model_name='seatmatrix',
            old_name='gmr',
            new_name='_gmr',
        ),
        migrations.RenameField(
            model_name='seatmatrix',
            old_name='gmrh',
            new_name='_gmrh',
        ),
        migrations.RenameField(
            model_name='seatmatrix',
            old_name='jk',
            new_name='_jk',
        ),
        migrations.RenameField(
            model_name='seatmatrix',
            old_name='ncc',
            new_name='_ncc',
        ),
        migrations.RenameField(
            model_name='seatmatrix',
            old_name='ph',
            new_name='_ph',
        ),
        migrations.RenameField(
            model_name='seatmatrix',
            old_name='scg',
            new_name='_scg',
        ),
        migrations.RenameField(
            model_name='seatmatrix',
            old_name='scgh',
            new_name='_scgh',
        ),
        migrations.RenameField(
            model_name='seatmatrix',
            old_name='sck',
            new_name='_sck',
        ),
        migrations.RenameField(
            model_name='seatmatrix',
            old_name='sckh',
            new_name='_sckh',
        ),
        migrations.RenameField(
            model_name='seatmatrix',
            old_name='scr',
            new_name='_scr',
        ),
        migrations.RenameField(
            model_name='seatmatrix',
            old_name='scrh',
            new_name='_scrh',
        ),
        migrations.RenameField(
            model_name='seatmatrix',
            old_name='sg',
            new_name='_sg',
        ),
        migrations.RenameField(
            model_name='seatmatrix',
            old_name='snq',
            new_name='_snq',
        ),
        migrations.RenameField(
            model_name='seatmatrix',
            old_name='spo',
            new_name='_spo',
        ),
        migrations.RenameField(
            model_name='seatmatrix',
            old_name='stg',
            new_name='_stg',
        ),
        migrations.RenameField(
            model_name='seatmatrix',
            old_name='stgh',
            new_name='_stgh',
        ),
        migrations.RenameField(
            model_name='seatmatrix',
            old_name='stk',
            new_name='_stk',
        ),
        migrations.RenameField(
            model_name='seatmatrix',
            old_name='stkh',
            new_name='_stkh',
        ),
        migrations.RenameField(
            model_name='seatmatrix',
            old_name='str',
            new_name='_str',
        ),
        migrations.RenameField(
            model_name='seatmatrix',
            old_name='strh',
            new_name='_strh',
        ),
        migrations.RenameField(
            model_name='seatmatrix',
            old_name='xcp',
            new_name='_xcp',
        ),
        migrations.RenameField(
            model_name='seatmatrix',
            old_name='xd',
            new_name='_xd',
        ),
        migrations.RemoveField(
            model_name='seatmatrix',
            name='accreditation',
        ),
        migrations.RemoveField(
            model_name='seatmatrix',
            name='affiliation',
        ),
        migrations.RemoveField(
            model_name='seatmatrix',
            name='annexure',
        ),
        migrations.RemoveField(
            model_name='seatmatrix',
            name='college_code',
        ),
        migrations.RemoveField(
            model_name='seatmatrix',
            name='college_operation',
        ),
        migrations.RemoveField(
            model_name='seatmatrix',
            name='college_ownership_type',
        ),
        migrations.RemoveField(
            model_name='seatmatrix',
            name='college_short_name',
        ),
        migrations.RemoveField(
            model_name='seatmatrix',
            name='district',
        ),
        migrations.RemoveField(
            model_name='seatmatrix',
            name='seat_type',
        ),
        migrations.RemoveField(
            model_name='seatmatrix',
            name='total',
        ),
        migrations.RemoveField(
            model_name='seatmatrix',
            name='year',
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='_accreditation',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Accreditation'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='_affiliation',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Affiliation'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='_anglo_indian',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anglo Indian'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='_annexure',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Annexure'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='_college_code',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='College Code'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='_college_operation',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='College Operation'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='_college_ownership_type',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='College Ownership Type'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='_college_short_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='College Short Name'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='_contact_number',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Contact Number'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='_courese_type',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Courese Type'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='_district',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='_email_i_d',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Email I D'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='_gmp',
            field=models.IntegerField(blank=True, null=True, verbose_name='GMP'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='_gmph',
            field=models.IntegerField(blank=True, null=True, verbose_name='GMPH'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='_govt_fees',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Govt Fees'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='_ma',
            field=models.IntegerField(blank=True, null=True, verbose_name='MA'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='_management',
            field=models.IntegerField(blank=True, null=True, verbose_name='Management'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='_management_fees',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Management Fees'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='_mc',
            field=models.IntegerField(blank=True, null=True, verbose_name='MC'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='_me',
            field=models.IntegerField(blank=True, null=True, verbose_name='ME'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='_meh',
            field=models.IntegerField(blank=True, null=True, verbose_name='MEH'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='_mk',
            field=models.IntegerField(blank=True, null=True, verbose_name='MK'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='_mm',
            field=models.IntegerField(blank=True, null=True, verbose_name='MM'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='_mmh',
            field=models.IntegerField(blank=True, null=True, verbose_name='MMH'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='_mu',
            field=models.IntegerField(blank=True, null=True, verbose_name='MU'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='_nri',
            field=models.IntegerField(blank=True, null=True, verbose_name='NRI'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='_opn',
            field=models.IntegerField(blank=True, null=True, verbose_name='OPN'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='_oth',
            field=models.IntegerField(blank=True, null=True, verbose_name='OTH'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='_rc2',
            field=models.IntegerField(blank=True, null=True, verbose_name='RC2'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='_rc3',
            field=models.IntegerField(blank=True, null=True, verbose_name='RC3'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='_rc4',
            field=models.IntegerField(blank=True, null=True, verbose_name='RC4'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='_rc5',
            field=models.IntegerField(blank=True, null=True, verbose_name='RC5'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='_rc6',
            field=models.IntegerField(blank=True, null=True, verbose_name='RC6'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='_rc7',
            field=models.IntegerField(blank=True, null=True, verbose_name='RC7'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='_rc8',
            field=models.IntegerField(blank=True, null=True, verbose_name='RC8'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='_seat_type',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Seat Type'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='_total_approved_intake',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Approved Intake'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='_total_reserved_seats',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Reserved Seats'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='_year',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Year'),
        ),
    ]
