# Generated by Django 4.2 on 2023-04-10 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_agl_seatmatrix__agl_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seatmatrix',
            old_name='_courese_type',
            new_name='_course_type',
        ),
    ]
