# Generated by Django 4.2 on 2023-05-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename__courese_type_seatmatrix__course_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NEETSeatMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_institue', models.CharField(blank=True, choices=[('AIIMS', 'AIIMS'), ('Except Central University', 'Except Central University'), ('Central University', 'Central University'), ('Deemed', 'Deemed'), ('ESI Scheme', 'ESI Scheme'), ('Jamia', 'Jamia'), ('JIPMER', 'JIPMER')], max_length=30, null=True)),
                ('state', models.CharField(blank=True, choices=[('Punjab', 'Punjab'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Assam', 'Assam'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Gujarat', 'Gujarat'), ('Odissa', 'Odissa'), ('Telangana', 'Telangana'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Rajasthan', 'Rajasthan'), ('Tamil Nadu', 'Tamil Nadu'), ('Maharastra', 'Maharastra'), ('Delhi', 'Delhi'), ('Bihar', 'Bihar'), ('Chattisgarh', 'Chattisgarh'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Jharkhand', 'Jharkhand'), ('West Bengal', 'West Bengal'), ('Goa', 'Goa'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Kerala', 'Kerala'), ('Karnataka', 'Karnataka'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Andaman & Nicobar', 'Andaman & Nicobar')], max_length=20, null=True)),
                ('institute', models.CharField(blank=True, max_length=150, null=True)),
                ('college_code', models.IntegerField(blank=True, null=True)),
                ('program', models.CharField(blank=True, choices=[('MBBS', 'MBBS'), ('BDS', 'BDS')], max_length=5, null=True)),
                ('quota', models.CharField(blank=True, choices=[('Open Seat Quota', 'Open Seat Quota'), ('Foreign Country Quota', 'Foreign Country Quota'), ('All India', 'All India'), ('Aligarh Muslim University (AMU) Quota', 'Aligarh Muslim University (AMU) Quota'), ('Non-Resident\nIndian(AMU)Quota', 'Non-Resident\nIndian(AMU)Quota'), ('IP University Quota', 'IP University Quota'), ('Delhi University Quota', 'Delhi University Quota'), ('Delhi NCR Children/Widows of Personnel of the Armed Forces (CW) Quota', 'Delhi NCR Children/Widows of Personnel of the Armed Forces (CW) Quota'), ('Non-Resident Indian', 'Non-Resident Indian'), ('Deemed/Paid Seats Quota', 'Deemed/Paid Seats Quota'), ('Jain Minority Quota', 'Jain Minority Quota'), ('Muslim Minority Quota', 'Muslim Minority Quota'), ('Employees State Insurance Scheme(ESI)', 'Employees State Insurance Scheme(ESI)'), ('Employees State Insurance\nScheme(ESI)', 'Employees State Insurance\nScheme(ESI)'), ('Jamia Internal Quota', 'Jamia Internal Quota'), ('Muslim OBC Quota', 'Muslim OBC Quota'), ('Muslim ST Quota', 'Muslim ST Quota'), ('Muslim Quota', 'Muslim Quota'), ('Muslim Women Quota', 'Muslim Women Quota'), ('Internal -Puducherry UT\nDomicile', 'Internal -Puducherry UT\nDomicile')], max_length=80, null=True)),
                ('open', models.IntegerField(blank=True, null=True)),
                ('open_pwd', models.IntegerField(blank=True, null=True)),
                ('general_ews', models.IntegerField(blank=True, null=True)),
                ('general_ews_pwd', models.IntegerField(blank=True, null=True)),
                ('obc', models.IntegerField(blank=True, null=True)),
                ('obc_pwd', models.IntegerField(blank=True, null=True)),
                ('sc', models.IntegerField(blank=True, null=True)),
                ('sc_pwd', models.IntegerField(blank=True, null=True)),
                ('st', models.IntegerField(blank=True, null=True)),
                ('st_pwd', models.IntegerField(blank=True, null=True)),
                ('total_seats', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='jeeorcr',
            name='year',
            field=models.CharField(choices=[('2022', '2022'), ('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016')], max_length=1000),
        ),
    ]
