# Generated by Django 4.2 on 2023-05-02 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_neetseatmatrix_alter_jeeorcr_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neetseatmatrix',
            old_name='type_of_institue',
            new_name='institute_type',
        ),
    ]
