# Generated by Django 4.2.1 on 2023-05-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_type_of_institue_neetseatmatrix_institute_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='neetseatmatrix',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='neetseatmatrix',
            name='owned_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
