# Generated by Django 4.2.1 on 2023-05-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_neetseatmatrix_city_neetseatmatrix_owned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='neetseatmatrix',
            name='affiliation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
