# Generated by Django 4.2.7 on 2023-11-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_neetseatmatrix_affiliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutoff',
            name='_1g',
            field=models.IntegerField(blank=True, null=True, verbose_name='1G'),
        ),
    ]
