# Generated by Django 4.2.7 on 2023-11-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_cutoff__1g'),
    ]

    operations = [
        migrations.AddField(
            model_name='neetseatmatrix',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='neetseatmatrix',
            name='institute_type',
            field=models.CharField(blank=True, choices=[('AIIMS', 'AIIMS'), ('Except Central University', 'Except Central University'), ('Central University', 'Central University'), ('Deemed University', 'Deemed University'), ('ESI Scheme', 'ESI Scheme'), ('Jamia', 'Jamia'), ('JIPMER', 'JIPMER')], max_length=30, null=True),
        ),
    ]
