# Generated by Django 4.2.7 on 2023-11-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_neetseatmatrix_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=1000)),
                ('college', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp_no', models.CharField(max_length=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='seatmatrix',
            name='_accreditation',
        ),
        migrations.RemoveField(
            model_name='seatmatrix',
            name='_affiliation',
        ),
    ]
