# Generated by Django 4.2.7 on 2023-12-03 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_admission_remove_seatmatrix__accreditation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admission',
        ),
    ]
